--- 
title: "Data and statistics with R"
author: "Jüri Lillemets"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::html_book
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: lillemets/datastatsr
description: "This is an introduction to quantitative data analysis with R"
---

# Preface {-}

Purposes of the course: quantitative data management, processing and analysis with R, tidying, description, visualization, statistical analysis.

Getting help: ? command, Stackoverflow

> R is a **language** and **environment** for **statistical computing** and **graphics**.

Based on S language orginating from 1970's. Developed during 1990's and became public around 2000.

Language and environment. 

- Programming language similar to any other but developed paricularly for data analysis. 
- Flexible and extensible environment as opposed to many statistical packages. 
- Command line interface.

Statistical computing and graphics.

- Includes many statistical procedures for various fields. 
- Constantly extended by the community with novel methods. 
- Abundant possibilities for plotting data

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

